[package]
name = "rust_core"
version = "0.1.0"
edition = "2021"
description = "."
repository = "https://github.com/tahavirdiwala/rust_core"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
